#!/bin/bash

######################################################
#   Compiles cqesar.cpp into the excutable caesar    #
######################################################

set -e    # halt on first error

# use 'clang++' as the compiler
CPP=clang++

# be aggressive about warnings and errors
FLAGS="-g -O -Wall -Wextra -Werror -Wfatal-errors -std=c++11 -pedantic"

# clear out old object files
rm -f *.o

# compile

$CPP $FLAGS -o caesar caesar.cpp